# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    messages:
        basename: classpath:/i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML
    social:
        # see https://developers.google.com/+/web/signin/server-side-flow#step_1_create_a_client_id_and_client_secret
        google:
            clientId: ${CLIENT_ID_GOOGLE}
            clientSecret: ${CLIENT_SECRET_GOOGLE}

        # see https://developers.facebook.com/docs/facebook-login/v2.2
        facebook:
            clientId: ${CLIENT_ID_FACEBOOK}
            clientSecret: ${CLIENT_SECRET_FACEBOOK}

        # see https://apps.twitter.com/app/
        twitter:
            clientId: ${CLIENT_ID_TWITTER}
            clientSecret: ${CLIENT_SECRET_TWITTER}

        # jhipster-needle-add-social-configuration

security:
    basic:
        enabled: false

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    cors: #By default CORS are not enabled. Uncomment to enable.
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers:
        allow-credentials: true
        max-age: 1800
    mail:
        from: backend@localhost
    security:
        rememberme:
            # security key (this key should be unique for your application, and kept secret)
            key: 7154c7ef48e5e2c1f37dfb6bfab6465cf5eba973
    swagger:
        title: backend API
        description: backend API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contact:
        license:
        licenseUrl:
    social:
        redirectAfterSignIn: "/#/home"
